### ISSUE TITLE
Can't create user / auto-created admin password does not work

### ISSUE THREAD

**Issue by atomicpapa** [archivy/archivy-docker#3]
I have followed the directions in Application Setup to create an admin, however I get the following error

```
glenn@zeus:~/docker$ docker exec -it docker_archivy_1 archivy create-admin --password Stinky1303$ glenn
/usr/local/lib/python3.9/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
[2021-01-23 01:20:10,432] INFO in __init__: Archivy has created an admin user as it did not exist.
                            Username: 'admin', password: '6m7oKd_xh4B00iDkUXuVP8Idgx6es555vOryjknTm6s'

Usage: archivy [OPTIONS] COMMAND [ARGS]...
Try 'archivy --help' for help.

Error: No such command 'create-admin'.

```
and when I try 'archivy --help'` I get

```
glenn@zeus:~/docker$ docker exec -it docker_archivy_1 archivy --help
/usr/local/lib/python3.9/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't mat                                                                                    ch a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Usage: archivy [OPTIONS] COMMAND [ARGS]...

Options:
  --version  Show the flask version
  --help     Show this message and exit.

Commands:
  routes  Show the routes for the app.
  run     Runs archivy web application
  shell   Run a shell in the app context.
```
Now that wouldn't necessarily be a problem except when I try to login with the password shown, I am told that my credentials are invalid.

![image](https://user-images.githubusercontent.com/6396499/105565074-a5e0ae00-5cea-11eb-81fd-3db22ac939e1.png)

Any help with how to proceed would be greatly appreciated!

**Comment by Uzay-G** [comment]
How did you setup the docker instance? It seems that your version of archivy is outdated

**Comment by piedoom** [comment]
Also having this error. I'm using Docker and pulling the latest image (appears to not have been updated in 2 months, unsure if that means anything)

**Comment by Uzay-G** [comment]
> Also having this error. I'm using Docker and pulling the latest image (appears to not have been updated in 2 months, unsure if that means anything)

What docs did you follow? The latest image was updated 3 days ago at https://hub.docker.com/repository/docker/uzayg/archivy.

**Comment by Uzay-G** [comment]
Since this is the second time people say this maybe they're's outdated docs somewhere? Could you tell me where you found the instructions for install?

Thanks :)

**Comment by piedoom** [comment]
Hi @Uzay-G! There appears to be two images: `harshavardhanj/archivy` and `uzayg/archivy` - I followed the original [README](https://github.com/archivy/archivy-docker/commit/2e16f4806dcf30124a8b93a4cc47fdfa34cb8563#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3) which now appears to have changed to remove that reference. My guess is that people may be searching the image on dockerhub, and selecting the first as it has many more pulls.

This may warrant opening a separate issue, but I've gone ahead and updated my old image to use the newer one - however, the page no longer seems to resolve. I'm using nginx and getting a 502.

**Comment by Uzay-G** [comment]
Hmm there have been some more changes recently, open an issue if you're still having issues :)
